on:
  workflow_dispatch:
  
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo "Hello World!"
    - run: git status
    # - run: git remote add origin https://github.com/vireshp/vireshp.git
    - run: git remote -v
    - run: git pull
    - run: git status
    - run: echo "Hello again World!"
    - run: git push remote main
